CREATE SCHEMA IF NOT EXISTS back_to_orm AUTHORIZATION admin;

CREATE SEQUENCE IF NOT EXISTS back_to_orm.book_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE book (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    price NUMERIC(19,2) NOT NULL
);